language: go

go:
- 1.9

before_install:
- go get -u github.com/golang/dep/cmd/dep
- go get -u github.com/alecthomas/gometalinter
- $GOPATH/bin/gometalinter --install

install:
- $GOPATH/bin/dep ensure

script:
- go test -v ./...
- $GOPATH/bin/gometalinter --config=.metalinter.json ./...

notifications:
  email: false
